/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.app.core.inuha.views.quanly.components.table.trangthai;

import com.app.utils.ColorUtils;
import com.app.utils.ProductUtils;
import java.awt.Color;

/**
 *
 * @author inuHa
 */
public class InuhaTrangThaiSanPhamTablePanel extends javax.swing.JPanel {

    /** Creates new form InuhaTrangThaiSanPhamTablePanel */
    public InuhaTrangThaiSanPhamTablePanel() {
	initComponents();
    }
    
    public InuhaTrangThaiSanPhamTablePanel(boolean trangThai) {
	this();
	pnlContainer.setOpaque(false);
	txtText.setForeground(Color.WHITE);
	setTrangThai(trangThai);
    }
    
    public void setTrangThai(boolean trangThai) { 
	if (trangThai) {
	    setDangBan();
	} else {
	    setNgungBan();
	}
    }
    
    public void setDangBan() { 
	txtText.setText(ProductUtils.getTrangThai(true));
	txtText.setForeground(ColorUtils.PRIMARY_COLOR);
    }

    public void setNgungBan() { 
	txtText.setText(ProductUtils.getTrangThai(false));
	txtText.setForeground(ColorUtils.DANGER_COLOR);
    }
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new com.app.views.UI.panel.RoundPanel();
        txtText = new javax.swing.JLabel();

        txtText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtText.setText("Ngừng bán");

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.app.views.UI.panel.RoundPanel pnlContainer;
    private javax.swing.JLabel txtText;
    // End of variables declaration//GEN-END:variables

}
